version: '3.8'

services:
  web:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: myapp-web
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./publish:/app
    command: sh -c "cd /app && dotnet PromoCodeFactory.WebHost.dll.dll --urls=\'http://0.0.0.0:5000\' --environment Production"

    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: myapp-db
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: